src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Entity\Employe;
use App\Entity\ResponsableRH;
use App\Entity\Developpeur;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[ORM\InheritanceType("JOINED")]
#[ORM\DiscriminatorColumn(name:"type", type:"string")]
#[ORM\DiscriminatorMap(['employee' => Employe::class, 'responsable' => ResponsableRH::class,'developpeur'=> Developpeur::class])]

abstract class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/SecurityType.php
<?php

namespace App\Form;
use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class SecurityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class,['label'=> false, 'attr' => ['class'=> 'w3-input w3-border', 'placeholder' => 'Email']])
            ->add('password', PasswordType::class,['label'=> false, 'attr' => ['class'=> 'w3-section w3-input w3-border', 'placeholder' => 'Mot de passe']])
            ->add('envoyer', SubmitType::class,['label'=> 'Envoyer', 'attr' => ['class'=> 'w3-button w3-black w3-section']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Form\SecurityType;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Developpeur;
use App\Entity\Projet;
use App\Entity\Tache;


use Doctrine\ORM\EntityManagerInterface;

class SecurityController extends AbstractController
{
    #[Route(path: '/backoffice', name: 'app_login')]
    public function login(EntityManagerInterface $doctrine,Request $request, AuthenticationUtils $authenticationUtils): Response
    {   
        $form = $this->createForm(SecurityType::class);
        $form->handleRequest($request);
        //$projets = $this->getDoctrine()->getRepository(Developpeur::class)->getProjet($this->getUser());
        //$projets = $this->getUser()->getEquipes();
        //$projets = $doctrine->getRepository(Developpeur::class)->getProjet(3);
        //dump($projets);
        if ($form->isSubmitted() && $form->isValid()) {
        }
        $user =$this->getUser();
        $projets = null;
        $countTache = null;
        if($user instanceof Developpeur){
            $projets = $this->getDoctrine()->getRepository(Projet::class)->findByDev($user->getId());
            $countTache = $this->getDoctrine()->getRepository(Tache::class)->getCountByDev($user->getId());

        }
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
            'loginForm' => $form->createView(),
            'projets' => $projets,
            'countTache' => $countTache
        ]);

        
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): Response
    {   
        
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
        
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Backoffice{% endblock %}

{% block body %}
<form method="post">
    {% if error %}
    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}

    <div class="w3-container w3-center">
        <h1>Bienvenue <strong>{{app.user.prenom}}</strong> dans votre backoffice !</h1>
    </div>
    <!--On vérifie que le user contient l'attribut annonce pour vérifier que c'est un employeRH-->
    {% if app.user.annonces is defined %}
    <div class="w3-container w3-center">
        <h2>Liste des fonctionnalités</h2>
        <p>Ici vous pourrez ajouter des employés, des annonces mais égalemment modifier les informations d'un employé (son salaire)</p>
        <a href="{{path('app_ajout_employerh')}}" class="w3-button w3-black">Ajouter un employé RH</a>
        <a href="{{path('app_ajout_developpeur')}}" class="w3-button w3-black">Ajouter un développeur</a>
        <!--Redéfinir le path lorsque la partie annonce sera fini-->
        <a href="{{path('app_annonce')}}" class="w3-button w3-black">Ajouter une annonce</a>
        <a href="{{path('app_show_employe')}}" class="w3-button w3-black">Liste des employés</a>
    </div>
    {% endif %}

    <!--On vérifie que le user contient l'attribut annonce pour vérifier que c'est un Dev-->
    {% if app.user.equipes is defined %}
    <div class="w3-container w3-center">
        <p>Vous avez actuellement <strong>{{countTache[1]}}</strong> taches.</p>
        <h2>Liste des fonctionnalités</h2>
        <p>Ici vous pourrez voir vos projets en cours, votre liste de taches</p>
        <a href="{{path('app_projet')}}" class="w3-button w3-black">Ajouter un nouveau projet</a>
        <a href="{{path('app_equipe')}}" class="w3-button w3-black">Ajouter une equipe</a>
        <h2>Liste de vos projets en cours</h2>
        <p>Vous pouvez visualiser le nombres de taches restantes juste à côté du projet</p>
        {% for p in projets %}
        <a href="{{path('app_un_projet', { id:p.id }) }}" class="w3-button w3-grey">{{p.nomProjet}}
            <span class="w3-badge w3-red">{{p.taches|filter(t => t.estFaite == false)|length}}</span>
            <span class="w3-badge w3-green">{{p.taches|filter(t => t.estFaite == true)|length}}</span>
        </a>
        {% endfor %}

    </div>
    {% endif %}

    {% else %}
    <!-- <label for="inputEmail">Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
                <label for="inputPassword">Password</label>
                <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
                <button class="btn btn-lg btn-primary" type="submit">
                    Sign in
                </button>
                -->

    <div class="w3-container w3-center" style="margin-left: auto; margin-right: auto; margin-top:0px; width: 70%; height: 800px; background: url({{ asset('images/stockOffice.jpg') }}) no-repeat 0 100%; background-size: cover;">
        <div class="w3-container w3-center" style="width:30%; height: 575px; border: 1px black solid;position: absolute; margin: auto; top:0; bottom: 0; left: 0; right: 0; background-color: rgba(255, 255, 255, .9)">
            <img src="{{ asset('images/logo-noBG.png') }}" style="width: 27%; height: 22%;">
            <br>
            <h1 class="h3 mb-3 font-weight-normal">Veuillez vous connecter.</h1>
            <input type="email" placeholder="Email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control w3-input w3-border" autocomplete="email" required autofocus><br>
            <input type="password" placeholder="Mot de passe" name="password" id="inputPassword" class="form-control w3-input w3-border" autocomplete="current-password" required><br>
            <button class="w3-button w3-black w3-section" type="submit" id='connexion'>
                Connexion
            </button>
            <a href="{{path('app_forgot_password_request')}}" class="w3-button w3-black">Mot de passe oublié ?</a>
        </div>
    </div>

    <!--
    <img src="{{ asset('images/stockOffice.jpg') }}" style="width: 60%; height: 60%;">
    -->

    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}
    {% endif %}


</form>
{% endblock %}
{% block script %}
{{ encore_entry_script_tags('connexionjs') }}

{% endblock %}